#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataEntry
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="InsiteFO")]
	public partial class DataEntryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DataEntryDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["InsiteFOConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataEntryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEntryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEntryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataEntryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.GetProducts")]
		public ISingleResult<GetProductsResult> GetProducts([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Search", DbType="VarChar(20)")] string search)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), search);
			return ((ISingleResult<GetProductsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.GetCategories")]
		public ISingleResult<GetCategoriesResult> GetCategories([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ParentId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> parentId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), parentId);
			return ((ISingleResult<GetCategoriesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.GetInfoTemplates")]
		public ISingleResult<GetInfoTemplatesResult> GetInfoTemplates()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetInfoTemplatesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.GetProductAttributes")]
		public ISingleResult<GetProductAttributesResult> GetProductAttributes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemNumber", DbType="VarChar(20)")] string itemNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), itemNumber);
			return ((ISingleResult<GetProductAttributesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.GetProduct")]
		public ISingleResult<GetProductResult> GetProduct([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemNumber", DbType="VarChar(20)")] string itemNumber)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), itemNumber);
			return ((ISingleResult<GetProductResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.GetAllVariants")]
		public ISingleResult<GetAllVariantsResult> GetAllVariants()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllVariantsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.GetProductVariants")]
		public ISingleResult<GetProductVariantsResult> GetProductVariants([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> productID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productID);
			return ((ISingleResult<GetProductVariantsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.GetUpdateStyleTraitValues")]
		public ISingleResult<GetUpdateStyleTraitValuesResult> GetUpdateStyleTraitValues([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StyleTraitID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> styleTraitID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), styleTraitID);
			return ((ISingleResult<GetUpdateStyleTraitValuesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.GetAllStyleTraitValues")]
		public ISingleResult<GetAllStyleTraitValuesResult> GetAllStyleTraitValues([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StyleClassID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> styleClassID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), styleClassID);
			return ((ISingleResult<GetAllStyleTraitValuesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.GetStyleTraitValues")]
		public ISingleResult<GetStyleTraitValuesResult> GetStyleTraitValues([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StyleTraitID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> styleTraitID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), styleTraitID);
			return ((ISingleResult<GetStyleTraitValuesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.UpdateStyleTraitValueSortOrder")]
		public int UpdateStyleTraitValueSortOrder([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StyleTraitValueID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> styleTraitValueID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifiedBy", DbType="VarChar(80)")] string modifiedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), styleTraitValueID, sortOrder, modifiedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.UpdateProductAttributes")]
		public int UpdateProductAttributes([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AttributeValueIds", DbType="VarChar(MAX)")] string attributeValueIds)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productId, attributeValueIds);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.UpdateStyleTraitValueProducts")]
		public int UpdateStyleTraitValueProducts([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StyleTraitValueIds", DbType="VarChar(MAX)")] string styleTraitValueIds)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productId, styleTraitValueIds);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.SwitchStyleTraitPositions")]
		public int SwitchStyleTraitPositions([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StyleTraitIds", DbType="VarChar(MAX)")] string styleTraitIds, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifiedBy", DbType="VarChar(80)")] string modifiedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), styleTraitIds, modifiedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.InsertVariantParent")]
		public ISingleResult<InsertVariantParentResult> InsertVariantParent([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemNumber", DbType="NVarChar(20)")] string itemNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShortDescription", DbType="NVarChar(2048)")] string shortDescription, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="MetaDescription", DbType="NVarChar(MAX)")] string metaDescription, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PleaseNotes", DbType="VarChar(8000)")] string pleaseNotes, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifiedBy", DbType="VarChar(80)")] string modifiedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), itemNumber, shortDescription, metaDescription, pleaseNotes, modifiedBy);
			return ((ISingleResult<InsertVariantParentResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.InsertAttributeValue")]
		public ISingleResult<InsertAttributeValueResult> InsertAttributeValue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AttributeTypeId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> attributeTypeId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AttributeValue", DbType="NVarChar(255)")] string attributeValue, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifiedBy", DbType="VarChar(80)")] string modifiedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), attributeTypeId, attributeValue, modifiedBy);
			return ((ISingleResult<InsertAttributeValueResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.InsertStyleTrait")]
		public ISingleResult<InsertStyleTraitResult> InsertStyleTrait([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StyleClassID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> styleClassID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Name", DbType="NVarChar(255)")] string name, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifiedBy", DbType="VarChar(80)")] string modifiedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), styleClassID, name, sortOrder, modifiedBy);
			return ((ISingleResult<InsertStyleTraitResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.InsertStyleTraitValue")]
		public ISingleResult<InsertStyleTraitValueResult> InsertStyleTraitValue([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StyleTraiteID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> styleTraiteID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Value", DbType="NVarChar(255)")] string value, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SortOrder", DbType="Int")] System.Nullable<int> sortOrder, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifiedBy", DbType="VarChar(80)")] string modifiedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), styleTraiteID, value, sortOrder, modifiedBy);
			return ((ISingleResult<InsertStyleTraitValueResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.GetAttributeTypeSettings")]
		public ISingleResult<GetAttributeTypeSettingsResult> GetAttributeTypeSettings()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAttributeTypeSettingsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.InsertError")]
		public int InsertError([global::System.Data.Linq.Mapping.ParameterAttribute(Name="UserName", DbType="VarChar(80)")] string userName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Message", DbType="VarChar(4000)")] string message, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="StackTrace", DbType="VarChar(MAX)")] string stackTrace, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Source", DbType="VarChar(1000)")] string source)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), userName, message, stackTrace, source);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.GetProductAndCategoryAttributesAndValues")]
		public ISingleResult<GetProductAndCategoryAttributesAndValuesResult> GetProductAndCategoryAttributesAndValues([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemNumber", DbType="VarChar(20)")] string itemNumber, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> categoryId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), itemNumber, categoryId);
			return ((ISingleResult<GetProductAndCategoryAttributesAndValuesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.UpdateProduct")]
		public int UpdateProduct(
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> productID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ItemNumber", DbType="NVarChar(20)")] string itemNumber, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ShortDescription", DbType="NVarChar(2048)")] string shortDescription, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="CategoryId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> categoryId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="InfoTemplateId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> infoTemplateId, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AvailableInKitSetAsst", DbType="VarChar(8000)")] string availableInKitSetAsst, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MetaDescription", DbType="NVarChar(MAX)")] string metaDescription, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="AdditionalSpecs", DbType="VarChar(8000)")] string additionalSpecs, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PleaseNotes", DbType="VarChar(8000)")] string pleaseNotes, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="MetaKeywords", DbType="NVarChar(MAX)")] string metaKeywords, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="KitSetincludes", DbType="VarChar(8000)")] string kitSetincludes, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="NewItemMeetingDate", DbType="VarChar(8000)")] string newItemMeetingDate, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="PrintGridDesc", DbType="VarChar(8000)")] string printGridDesc, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProdCatSection", DbType="VarChar(8000)")] string prodCatSection, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProdPageNmbr", DbType="VarChar(8000)")] string prodPageNmbr, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductnamePrint", DbType="VarChar(8000)")] string productnamePrint, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductPrintDesc", DbType="VarChar(8000)")] string productPrintDesc, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="StyleClassID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> styleClassID, 
					[global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifiedBy", DbType="VarChar(80)")] string modifiedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productID, itemNumber, shortDescription, categoryId, infoTemplateId, availableInKitSetAsst, metaDescription, additionalSpecs, pleaseNotes, metaKeywords, kitSetincludes, newItemMeetingDate, printGridDesc, prodCatSection, prodPageNmbr, productnamePrint, productPrintDesc, styleClassID, modifiedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.GetProductsInStyleClass")]
		public ISingleResult<GetProductsInStyleClassResult> GetProductsInStyleClass([global::System.Data.Linq.Mapping.ParameterAttribute(Name="StyleClassID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> styleClassID)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), styleClassID);
			return ((ISingleResult<GetProductsInStyleClassResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.RemoveProductFromVariant")]
		public int RemoveProductFromVariant([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductID", DbType="UniqueIdentifier")] System.Nullable<System.Guid> productID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ModifiedBy", DbType="VarChar(80)")] string modifiedBy)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productID, modifiedBy);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.GetAllChemicals")]
		public ISingleResult<GetAllChemicalsResult> GetAllChemicals()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetAllChemicalsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.GetProductChemicals")]
		public ISingleResult<GetProductChemicalsResult> GetProductChemicals([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> productId)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productId);
			return ((ISingleResult<GetProductChemicalsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="DataEntry.UpdateProductChemicals")]
		public int UpdateProductChemicals([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ProductId", DbType="UniqueIdentifier")] System.Nullable<System.Guid> productId, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ChemicalIds", DbType="VarChar(MAX)")] string chemicalIds)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), productId, chemicalIds);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class GetProductsResult
	{
		
		private string _ShortDescription;
		
		private string _ERPNumber;
		
		private string _MetaDescription;
		
		public GetProductsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortDescription", DbType="NVarChar(2048) NOT NULL", CanBeNull=false)]
		public string ShortDescription
		{
			get
			{
				return this._ShortDescription;
			}
			set
			{
				if ((this._ShortDescription != value))
				{
					this._ShortDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ERPNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ERPNumber
		{
			get
			{
				return this._ERPNumber;
			}
			set
			{
				if ((this._ERPNumber != value))
				{
					this._ERPNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaDescription", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MetaDescription
		{
			get
			{
				return this._MetaDescription;
			}
			set
			{
				if ((this._MetaDescription != value))
				{
					this._MetaDescription = value;
				}
			}
		}
	}
	
	public partial class GetCategoriesResult
	{
		
		private System.Guid _Id;
		
		private string _Name;
		
		public GetCategoriesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class GetInfoTemplatesResult
	{
		
		private System.Guid _Id;
		
		private string _Name;
		
		public GetInfoTemplatesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class GetProductAttributesResult
	{
		
		private System.Guid _AttributeTypeId;
		
		private string _AttributeTypeName;
		
		private string _AttributeTypeLabel;
		
		private System.Guid _AttributeValueId;
		
		private string _AttributeValue;
		
		public GetProductAttributesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeTypeId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid AttributeTypeId
		{
			get
			{
				return this._AttributeTypeId;
			}
			set
			{
				if ((this._AttributeTypeId != value))
				{
					this._AttributeTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeTypeName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string AttributeTypeName
		{
			get
			{
				return this._AttributeTypeName;
			}
			set
			{
				if ((this._AttributeTypeName != value))
				{
					this._AttributeTypeName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeTypeLabel", DbType="NVarChar(1024) NOT NULL", CanBeNull=false)]
		public string AttributeTypeLabel
		{
			get
			{
				return this._AttributeTypeLabel;
			}
			set
			{
				if ((this._AttributeTypeLabel != value))
				{
					this._AttributeTypeLabel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeValueId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid AttributeValueId
		{
			get
			{
				return this._AttributeValueId;
			}
			set
			{
				if ((this._AttributeValueId != value))
				{
					this._AttributeValueId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeValue", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string AttributeValue
		{
			get
			{
				return this._AttributeValue;
			}
			set
			{
				if ((this._AttributeValue != value))
				{
					this._AttributeValue = value;
				}
			}
		}
	}
	
	public partial class GetProductResult
	{
		
		private System.Guid _Id;
		
		private string _ShortDescription;
		
		private string _ERPNumber;
		
		private string _ProductManager;
		
		private string _SupplyManager;
		
		private System.Nullable<System.Guid> _CategoryID;
		
		private string _Category;
		
		private string _CategoryPath;
		
		private System.Nullable<System.Guid> _InfoTemplateID;
		
		private string _InfoTemplate;
		
		private string _MetaDescription;
		
		private string _AdditionalSpecs;
		
		private string _PleaseNote;
		
		private string _AvailableInKitSetAsst;
		
		private string _KitSetincludes;
		
		private string _MetaKeywords;
		
		private string _SaleUomName;
		
		private string _CatalogPage;
		
		private string _NetWeight;
		
		private string _ShipWeight;
		
		private string _NewItemMeetingDate;
		
		private string _PrintGridDesc;
		
		private string _ProdCatSection;
		
		private string _ProdPageNmbr;
		
		private string _ProductnamePrint;
		
		private string _ProductPrintDesc;
		
		private string _CustomService;
		
		private string _IsExclusive;
		
		private System.Nullable<System.Guid> _ProductVariantID;
		
		private string _ProductVariantItemNumber;
		
		private System.Nullable<System.Guid> _ProductVariantStyleClassID;
		
		public GetProductResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortDescription", DbType="NVarChar(2048) NOT NULL", CanBeNull=false)]
		public string ShortDescription
		{
			get
			{
				return this._ShortDescription;
			}
			set
			{
				if ((this._ShortDescription != value))
				{
					this._ShortDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ERPNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ERPNumber
		{
			get
			{
				return this._ERPNumber;
			}
			set
			{
				if ((this._ERPNumber != value))
				{
					this._ERPNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductManager", DbType="VarChar(8000)")]
		public string ProductManager
		{
			get
			{
				return this._ProductManager;
			}
			set
			{
				if ((this._ProductManager != value))
				{
					this._ProductManager = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SupplyManager", DbType="VarChar(8000)")]
		public string SupplyManager
		{
			get
			{
				return this._SupplyManager;
			}
			set
			{
				if ((this._SupplyManager != value))
				{
					this._SupplyManager = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> CategoryID
		{
			get
			{
				return this._CategoryID;
			}
			set
			{
				if ((this._CategoryID != value))
				{
					this._CategoryID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Category", DbType="NVarChar(255)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this._Category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CategoryPath", DbType="NVarChar(MAX)")]
		public string CategoryPath
		{
			get
			{
				return this._CategoryPath;
			}
			set
			{
				if ((this._CategoryPath != value))
				{
					this._CategoryPath = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoTemplateID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> InfoTemplateID
		{
			get
			{
				return this._InfoTemplateID;
			}
			set
			{
				if ((this._InfoTemplateID != value))
				{
					this._InfoTemplateID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_InfoTemplate", DbType="NVarChar(255)")]
		public string InfoTemplate
		{
			get
			{
				return this._InfoTemplate;
			}
			set
			{
				if ((this._InfoTemplate != value))
				{
					this._InfoTemplate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaDescription", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MetaDescription
		{
			get
			{
				return this._MetaDescription;
			}
			set
			{
				if ((this._MetaDescription != value))
				{
					this._MetaDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdditionalSpecs", DbType="VarChar(8000)")]
		public string AdditionalSpecs
		{
			get
			{
				return this._AdditionalSpecs;
			}
			set
			{
				if ((this._AdditionalSpecs != value))
				{
					this._AdditionalSpecs = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PleaseNote", DbType="VarChar(8000)")]
		public string PleaseNote
		{
			get
			{
				return this._PleaseNote;
			}
			set
			{
				if ((this._PleaseNote != value))
				{
					this._PleaseNote = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AvailableInKitSetAsst", DbType="VarChar(8000)")]
		public string AvailableInKitSetAsst
		{
			get
			{
				return this._AvailableInKitSetAsst;
			}
			set
			{
				if ((this._AvailableInKitSetAsst != value))
				{
					this._AvailableInKitSetAsst = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KitSetincludes", DbType="VarChar(8000)")]
		public string KitSetincludes
		{
			get
			{
				return this._KitSetincludes;
			}
			set
			{
				if ((this._KitSetincludes != value))
				{
					this._KitSetincludes = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MetaKeywords", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string MetaKeywords
		{
			get
			{
				return this._MetaKeywords;
			}
			set
			{
				if ((this._MetaKeywords != value))
				{
					this._MetaKeywords = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SaleUomName", DbType="VarChar(8000)")]
		public string SaleUomName
		{
			get
			{
				return this._SaleUomName;
			}
			set
			{
				if ((this._SaleUomName != value))
				{
					this._SaleUomName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CatalogPage", DbType="VarChar(8000)")]
		public string CatalogPage
		{
			get
			{
				return this._CatalogPage;
			}
			set
			{
				if ((this._CatalogPage != value))
				{
					this._CatalogPage = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NetWeight", DbType="VarChar(8000)")]
		public string NetWeight
		{
			get
			{
				return this._NetWeight;
			}
			set
			{
				if ((this._NetWeight != value))
				{
					this._NetWeight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShipWeight", DbType="VarChar(8000)")]
		public string ShipWeight
		{
			get
			{
				return this._ShipWeight;
			}
			set
			{
				if ((this._ShipWeight != value))
				{
					this._ShipWeight = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NewItemMeetingDate", DbType="VarChar(8000)")]
		public string NewItemMeetingDate
		{
			get
			{
				return this._NewItemMeetingDate;
			}
			set
			{
				if ((this._NewItemMeetingDate != value))
				{
					this._NewItemMeetingDate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PrintGridDesc", DbType="VarChar(8000)")]
		public string PrintGridDesc
		{
			get
			{
				return this._PrintGridDesc;
			}
			set
			{
				if ((this._PrintGridDesc != value))
				{
					this._PrintGridDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdCatSection", DbType="VarChar(8000)")]
		public string ProdCatSection
		{
			get
			{
				return this._ProdCatSection;
			}
			set
			{
				if ((this._ProdCatSection != value))
				{
					this._ProdCatSection = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProdPageNmbr", DbType="VarChar(8000)")]
		public string ProdPageNmbr
		{
			get
			{
				return this._ProdPageNmbr;
			}
			set
			{
				if ((this._ProdPageNmbr != value))
				{
					this._ProdPageNmbr = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductnamePrint", DbType="VarChar(8000)")]
		public string ProductnamePrint
		{
			get
			{
				return this._ProductnamePrint;
			}
			set
			{
				if ((this._ProductnamePrint != value))
				{
					this._ProductnamePrint = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductPrintDesc", DbType="VarChar(8000)")]
		public string ProductPrintDesc
		{
			get
			{
				return this._ProductPrintDesc;
			}
			set
			{
				if ((this._ProductPrintDesc != value))
				{
					this._ProductPrintDesc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CustomService", DbType="VarChar(8000)")]
		public string CustomService
		{
			get
			{
				return this._CustomService;
			}
			set
			{
				if ((this._CustomService != value))
				{
					this._CustomService = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsExclusive", DbType="VarChar(8000)")]
		public string IsExclusive
		{
			get
			{
				return this._IsExclusive;
			}
			set
			{
				if ((this._IsExclusive != value))
				{
					this._IsExclusive = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductVariantID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ProductVariantID
		{
			get
			{
				return this._ProductVariantID;
			}
			set
			{
				if ((this._ProductVariantID != value))
				{
					this._ProductVariantID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductVariantItemNumber", DbType="NVarChar(50)")]
		public string ProductVariantItemNumber
		{
			get
			{
				return this._ProductVariantItemNumber;
			}
			set
			{
				if ((this._ProductVariantItemNumber != value))
				{
					this._ProductVariantItemNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductVariantStyleClassID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> ProductVariantStyleClassID
		{
			get
			{
				return this._ProductVariantStyleClassID;
			}
			set
			{
				if ((this._ProductVariantStyleClassID != value))
				{
					this._ProductVariantStyleClassID = value;
				}
			}
		}
	}
	
	public partial class GetAllVariantsResult
	{
		
		private System.Guid _StyleClassID;
		
		private string _Name;
		
		public GetAllVariantsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleClassID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid StyleClassID
		{
			get
			{
				return this._StyleClassID;
			}
			set
			{
				if ((this._StyleClassID != value))
				{
					this._StyleClassID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
	}
	
	public partial class GetProductVariantsResult
	{
		
		private System.Guid _ProductID;
		
		private System.Guid _StyleTraitID;
		
		private string _Name;
		
		private string _Description;
		
		private System.Guid _StyleTraitValueID;
		
		private string _Value;
		
		private int _SortOrder;
		
		public GetProductVariantsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this._ProductID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid StyleTraitID
		{
			get
			{
				return this._StyleTraitID;
			}
			set
			{
				if ((this._StyleTraitID != value))
				{
					this._StyleTraitID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="NVarChar(512) NOT NULL", CanBeNull=false)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this._Description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitValueID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid StyleTraitValueID
		{
			get
			{
				return this._StyleTraitValueID;
			}
			set
			{
				if ((this._StyleTraitValueID != value))
				{
					this._StyleTraitValueID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int NOT NULL")]
		public int SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this._SortOrder = value;
				}
			}
		}
	}
	
	public partial class GetUpdateStyleTraitValuesResult
	{
		
		private System.Guid _ID;
		
		private string _Value;
		
		private int _SortOrder;
		
		public GetUpdateStyleTraitValuesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SortOrder", DbType="Int NOT NULL")]
		public int SortOrder
		{
			get
			{
				return this._SortOrder;
			}
			set
			{
				if ((this._SortOrder != value))
				{
					this._SortOrder = value;
				}
			}
		}
	}
	
	public partial class GetAllStyleTraitValuesResult
	{
		
		private System.Guid _StyleClassID;
		
		private string _StyleClassName;
		
		private System.Guid _StyleTraitID;
		
		private string _StyleTraitName;
		
		private int _StyleTraitSortOrder;
		
		private string _StyleTraitDescription;
		
		private System.Nullable<System.Guid> _StyleTraitValueID;
		
		private string _StyleTraitValue;
		
		private System.Nullable<int> _StyleTraitValueSortOrder;
		
		public GetAllStyleTraitValuesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleClassID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid StyleClassID
		{
			get
			{
				return this._StyleClassID;
			}
			set
			{
				if ((this._StyleClassID != value))
				{
					this._StyleClassID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleClassName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string StyleClassName
		{
			get
			{
				return this._StyleClassName;
			}
			set
			{
				if ((this._StyleClassName != value))
				{
					this._StyleClassName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid StyleTraitID
		{
			get
			{
				return this._StyleTraitID;
			}
			set
			{
				if ((this._StyleTraitID != value))
				{
					this._StyleTraitID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string StyleTraitName
		{
			get
			{
				return this._StyleTraitName;
			}
			set
			{
				if ((this._StyleTraitName != value))
				{
					this._StyleTraitName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitSortOrder", DbType="Int NOT NULL")]
		public int StyleTraitSortOrder
		{
			get
			{
				return this._StyleTraitSortOrder;
			}
			set
			{
				if ((this._StyleTraitSortOrder != value))
				{
					this._StyleTraitSortOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitDescription", DbType="NVarChar(512) NOT NULL", CanBeNull=false)]
		public string StyleTraitDescription
		{
			get
			{
				return this._StyleTraitDescription;
			}
			set
			{
				if ((this._StyleTraitDescription != value))
				{
					this._StyleTraitDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitValueID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> StyleTraitValueID
		{
			get
			{
				return this._StyleTraitValueID;
			}
			set
			{
				if ((this._StyleTraitValueID != value))
				{
					this._StyleTraitValueID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitValue", DbType="NVarChar(255)")]
		public string StyleTraitValue
		{
			get
			{
				return this._StyleTraitValue;
			}
			set
			{
				if ((this._StyleTraitValue != value))
				{
					this._StyleTraitValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitValueSortOrder", DbType="Int")]
		public System.Nullable<int> StyleTraitValueSortOrder
		{
			get
			{
				return this._StyleTraitValueSortOrder;
			}
			set
			{
				if ((this._StyleTraitValueSortOrder != value))
				{
					this._StyleTraitValueSortOrder = value;
				}
			}
		}
	}
	
	public partial class GetStyleTraitValuesResult
	{
		
		private System.Guid _StyleTraitID;
		
		private string _StyleTraitName;
		
		private int _StyleTraitSortOrder;
		
		private string _StyleTraitDescription;
		
		private System.Nullable<System.Guid> _StyleTraitValueID;
		
		private string _StyleTraitValue;
		
		private System.Nullable<int> _StyleTraitValueSortOrder;
		
		public GetStyleTraitValuesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid StyleTraitID
		{
			get
			{
				return this._StyleTraitID;
			}
			set
			{
				if ((this._StyleTraitID != value))
				{
					this._StyleTraitID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitName", DbType="NVarChar(255) NOT NULL", CanBeNull=false)]
		public string StyleTraitName
		{
			get
			{
				return this._StyleTraitName;
			}
			set
			{
				if ((this._StyleTraitName != value))
				{
					this._StyleTraitName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitSortOrder", DbType="Int NOT NULL")]
		public int StyleTraitSortOrder
		{
			get
			{
				return this._StyleTraitSortOrder;
			}
			set
			{
				if ((this._StyleTraitSortOrder != value))
				{
					this._StyleTraitSortOrder = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitDescription", DbType="NVarChar(512) NOT NULL", CanBeNull=false)]
		public string StyleTraitDescription
		{
			get
			{
				return this._StyleTraitDescription;
			}
			set
			{
				if ((this._StyleTraitDescription != value))
				{
					this._StyleTraitDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitValueID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> StyleTraitValueID
		{
			get
			{
				return this._StyleTraitValueID;
			}
			set
			{
				if ((this._StyleTraitValueID != value))
				{
					this._StyleTraitValueID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitValue", DbType="NVarChar(255)")]
		public string StyleTraitValue
		{
			get
			{
				return this._StyleTraitValue;
			}
			set
			{
				if ((this._StyleTraitValue != value))
				{
					this._StyleTraitValue = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitValueSortOrder", DbType="Int")]
		public System.Nullable<int> StyleTraitValueSortOrder
		{
			get
			{
				return this._StyleTraitValueSortOrder;
			}
			set
			{
				if ((this._StyleTraitValueSortOrder != value))
				{
					this._StyleTraitValueSortOrder = value;
				}
			}
		}
	}
	
	public partial class InsertVariantParentResult
	{
		
		private System.Nullable<System.Guid> _StyleClassID;
		
		public InsertVariantParentResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleClassID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> StyleClassID
		{
			get
			{
				return this._StyleClassID;
			}
			set
			{
				if ((this._StyleClassID != value))
				{
					this._StyleClassID = value;
				}
			}
		}
	}
	
	public partial class InsertAttributeValueResult
	{
		
		private System.Nullable<System.Guid> _AttributeValueId;
		
		public InsertAttributeValueResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeValueId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> AttributeValueId
		{
			get
			{
				return this._AttributeValueId;
			}
			set
			{
				if ((this._AttributeValueId != value))
				{
					this._AttributeValueId = value;
				}
			}
		}
	}
	
	public partial class InsertStyleTraitResult
	{
		
		private System.Nullable<System.Guid> _StyleTraitID;
		
		public InsertStyleTraitResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> StyleTraitID
		{
			get
			{
				return this._StyleTraitID;
			}
			set
			{
				if ((this._StyleTraitID != value))
				{
					this._StyleTraitID = value;
				}
			}
		}
	}
	
	public partial class InsertStyleTraitValueResult
	{
		
		private System.Nullable<System.Guid> _StyleTraitValueID;
		
		public InsertStyleTraitValueResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitValueID", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> StyleTraitValueID
		{
			get
			{
				return this._StyleTraitValueID;
			}
			set
			{
				if ((this._StyleTraitValueID != value))
				{
					this._StyleTraitValueID = value;
				}
			}
		}
	}
	
	public partial class GetAttributeTypeSettingsResult
	{
		
		private System.Guid _AttributeTypeID;
		
		private string _Setting;
		
		public GetAttributeTypeSettingsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeTypeID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid AttributeTypeID
		{
			get
			{
				return this._AttributeTypeID;
			}
			set
			{
				if ((this._AttributeTypeID != value))
				{
					this._AttributeTypeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Setting", DbType="VarChar(50)")]
		public string Setting
		{
			get
			{
				return this._Setting;
			}
			set
			{
				if ((this._Setting != value))
				{
					this._Setting = value;
				}
			}
		}
	}
	
	public partial class GetProductAndCategoryAttributesAndValuesResult
	{
		
		private System.Guid _AttributeTypeId;
		
		private string _Name;
		
		private string _Label;
		
		private System.Guid _AttributeValueId;
		
		private string _Value;
		
		private bool _IsDefaultAttributeType;
		
		public GetProductAndCategoryAttributesAndValuesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeTypeId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid AttributeTypeId
		{
			get
			{
				return this._AttributeTypeId;
			}
			set
			{
				if ((this._AttributeTypeId != value))
				{
					this._AttributeTypeId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this._Name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Label", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Label
		{
			get
			{
				return this._Label;
			}
			set
			{
				if ((this._Label != value))
				{
					this._Label = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AttributeValueId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid AttributeValueId
		{
			get
			{
				return this._AttributeValueId;
			}
			set
			{
				if ((this._AttributeValueId != value))
				{
					this._AttributeValueId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="VarChar(1000) NOT NULL", CanBeNull=false)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsDefaultAttributeType", DbType="Bit NOT NULL")]
		public bool IsDefaultAttributeType
		{
			get
			{
				return this._IsDefaultAttributeType;
			}
			set
			{
				if ((this._IsDefaultAttributeType != value))
				{
					this._IsDefaultAttributeType = value;
				}
			}
		}
	}
	
	public partial class GetProductsInStyleClassResult
	{
		
		private System.Guid _ProductID;
		
		private string _ItemNumber;
		
		private System.Nullable<System.Guid> _StyleTraitId;
		
		private string _StyleTraitName;
		
		private string _StyleTraitDescription;
		
		private System.Nullable<System.Guid> _StyleTraitValueId;
		
		private string _StyleTraitValue;
		
		public GetProductsInStyleClassResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductID", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ProductID
		{
			get
			{
				return this._ProductID;
			}
			set
			{
				if ((this._ProductID != value))
				{
					this._ProductID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ItemNumber", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ItemNumber
		{
			get
			{
				return this._ItemNumber;
			}
			set
			{
				if ((this._ItemNumber != value))
				{
					this._ItemNumber = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> StyleTraitId
		{
			get
			{
				return this._StyleTraitId;
			}
			set
			{
				if ((this._StyleTraitId != value))
				{
					this._StyleTraitId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitName", DbType="NVarChar(255)")]
		public string StyleTraitName
		{
			get
			{
				return this._StyleTraitName;
			}
			set
			{
				if ((this._StyleTraitName != value))
				{
					this._StyleTraitName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitDescription", DbType="NVarChar(512)")]
		public string StyleTraitDescription
		{
			get
			{
				return this._StyleTraitDescription;
			}
			set
			{
				if ((this._StyleTraitDescription != value))
				{
					this._StyleTraitDescription = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitValueId", DbType="UniqueIdentifier")]
		public System.Nullable<System.Guid> StyleTraitValueId
		{
			get
			{
				return this._StyleTraitValueId;
			}
			set
			{
				if ((this._StyleTraitValueId != value))
				{
					this._StyleTraitValueId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StyleTraitValue", DbType="NVarChar(255)")]
		public string StyleTraitValue
		{
			get
			{
				return this._StyleTraitValue;
			}
			set
			{
				if ((this._StyleTraitValue != value))
				{
					this._StyleTraitValue = value;
				}
			}
		}
	}
	
	public partial class GetAllChemicalsResult
	{
		
		private System.Guid _Id;
		
		private string _Chemical;
		
		private string _TypeOfToxicity;
		
		public GetAllChemicalsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this._Id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chemical", DbType="VarChar(1000)")]
		public string Chemical
		{
			get
			{
				return this._Chemical;
			}
			set
			{
				if ((this._Chemical != value))
				{
					this._Chemical = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOfToxicity", DbType="VarChar(1000)")]
		public string TypeOfToxicity
		{
			get
			{
				return this._TypeOfToxicity;
			}
			set
			{
				if ((this._TypeOfToxicity != value))
				{
					this._TypeOfToxicity = value;
				}
			}
		}
	}
	
	public partial class GetProductChemicalsResult
	{
		
		private System.Guid _ProductChemicalsId;
		
		private System.Guid _ChemicalId;
		
		private string _Chemical;
		
		private string _TypeOfToxicity;
		
		public GetProductChemicalsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ProductChemicalsId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ProductChemicalsId
		{
			get
			{
				return this._ProductChemicalsId;
			}
			set
			{
				if ((this._ProductChemicalsId != value))
				{
					this._ProductChemicalsId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ChemicalId", DbType="UniqueIdentifier NOT NULL")]
		public System.Guid ChemicalId
		{
			get
			{
				return this._ChemicalId;
			}
			set
			{
				if ((this._ChemicalId != value))
				{
					this._ChemicalId = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chemical", DbType="VarChar(1000)")]
		public string Chemical
		{
			get
			{
				return this._Chemical;
			}
			set
			{
				if ((this._Chemical != value))
				{
					this._Chemical = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TypeOfToxicity", DbType="VarChar(1000)")]
		public string TypeOfToxicity
		{
			get
			{
				return this._TypeOfToxicity;
			}
			set
			{
				if ((this._TypeOfToxicity != value))
				{
					this._TypeOfToxicity = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
